### ISSUE TITLE
Add direct support to run Serversync when hosting server! Allows for easy share modded mini dedicated servers

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [jaideepheer/MinecraftForge-Mods-ServerPropertiesLAN#2] opened 2017-12-30 14:13 UTC
https://github.com/superzanti/ServerSync/issues/94

This would make lan servers easily be hosted and shared with users interested in joining.

**Comment by jaideepheer** [comment] 2018-01-05 11:14
It is a great idea, let me take a look at it.

**Comment by P3rf3ctXZer0** [comment] 2018-01-05 13:44
... Oh my God I remembered something I will run a test ... I forgot that server-sync can run as a forge mod.

**Comment by P3rf3ctXZer0** [comment] 2018-01-05 13:55
Okay right now serversync does not see lan as a dedicated server ergo it does not initialize.

**Comment by jaideepheer** [comment] 2018-01-06 07:59
Well... I think the problem here is that serversync has marked itself as a server-side only mod. Thus forge does not load it during the initialization of the client. This probably results in the lan host not having the serversync mod in the local world.

**Comment by P3rf3ctXZer0** [comment] 2018-01-06 14:45
@rheimus think you can make a few changes?

**Comment by rheimus** [comment] 2018-01-06 21:35
I'll have a look into options for running in a lan world.

Adding client side loading would make serversync a hard dependency for all clients though, which I would rather not enforce.

I could make a specific lan version of SS if there is no other way to detect that the game is running via lan.

**Comment by rheimus** [comment] 2018-01-06 21:53
If this is something you wish to do right now then SS can be started manually in server mode for lan hosts and used as normal.

**Comment by P3rf3ctXZer0** [comment] 2018-01-08 10:39
What about an optional hard dependency?

**Comment by rheimus** [comment] 2018-01-10 09:28
Forge will crash clients without serversync complaining about missing dependencies.

Can't really make it optional, I'm hoping that forge provides some what of discerning that a lan client is connected and hosting a server.

**Comment by jaideepheer** [comment] 2018-01-10 11:17
As a possible solution, you can start off by removing the server-only marking thus allowing forge to load it on a client. This is required because a LAN server is run on the client instead of the dedicated server.

Now I suppose that you need to run the code after the server starts up. This can be easily detected by using forge's `FMLServerStartingEvent` FML Event.
This, however, tells you that an SP world has started the game. To know when it is open to LAN, check out the `HttpUtil#getSuitableLanPort()` in the `net.minecraft.HttpUtil` class. SPLAN(this mod) modifies this function via ASM to get it to return a custom port. It is called whenever a world is opened to LAN.

If you want me to make an API to provide sever events/data like LAN status or current port etc I can easily do it but then serversync would require SPLAN to work with LAN worlds.

**Comment by P3rf3ctXZer0** [comment] 2018-01-10 12:40
@rheimus what about releasing two versions?

**Comment by jaideepheer** [comment] 2018-01-11 13:26
I think is that just one version is possible. Some wrapper code to detect if its LAN or not can simply run the mod in the appropriate folder.
Unless there are other complications like server-side only code etc.

**Comment by rheimus** [comment] 2018-01-16 08:10
Hmm, thanks for the info 😄.

I'll see what I can get working.

**Comment by jaideepheer** [comment] 2018-02-03 04:21
@P3rf3ctXZer0 If this issue is resolved please close it.

**Comment by P3rf3ctXZer0** [comment] 2018-02-03 06:25
Its not fixed yet. That I know of is it @rheimus

**Closed** 2018-02-03 06:25 UTC
Labels: enhancement, foriegn

**Comment by rheimus** [comment] 2018-02-03 07:15
The issue is pure serversync side at the moment so yeah for this project the issue is resolved :)
